# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.8
            - g++-5
            - gcc-5
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libwayland-dev
            - libx11-xcb-dev
            - libx11-dev
            - libgbm-dev

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  - clang

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DKMSXX_ENABLE_KMSCUBE=1 -DKMSXX_ENABLE_PYTHON=1 .. && make
