# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: cpp

# Need MYCC and MYCXX as travis overwrites CC and CXX

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8', 'libegl1-mesa-dev', 'libgles2-mesa-dev', 'libwayland-dev',  'libx11-xcb-dev',  'libx11-dev',  'libgbm-dev']
      env: MYCC=gcc-4.8 MYCXX=g++-4.8

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libegl1-mesa-dev', 'libgles2-mesa-dev', 'libwayland-dev',  'libx11-xcb-dev',  'libx11-dev',  'libgbm-dev']
      env: MYCC=gcc-4.9 MYCXX=g++-4.9

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libegl1-mesa-dev', 'libgles2-mesa-dev', 'libwayland-dev',  'libx11-xcb-dev',  'libx11-dev',  'libgbm-dev']
      env: MYCC=gcc-5 MYCXX=g++-5

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8', 'libegl1-mesa-dev', 'libgles2-mesa-dev', 'libwayland-dev',  'libx11-xcb-dev',  'libx11-dev',  'libgbm-dev']
      env: MYCC=clang-3.8 MYCXX=clang++-3.8

# Build steps
script:
  - mkdir build
  - cd build
  - CC=$MYCC CXX=$MYCXX cmake -DKMSXX_ENABLE_KMSCUBE=1 -DKMSXX_ENABLE_PYTHON=1 .. && make
